
GET http://localhost:4004/odata/v4/catservice/ReadEmpSet

### CREATE
POST http://localhost:4004/odata/v4/catservice/CreateEmpSet
Content-Type: application/json


{
        "EMPID": 103,
        "EMPNAME": "Suman",
        "GENDER": "M",
        "SALARY": 43400        
}

### CREATE
POST http://localhost:4004/odata/v4/catservice/CreateEmpSet
Content-Type: application/json

{
        "EMPID": 104,
        "EMPNAME": "Sushma",
        "GENDER": "F",
        "SALARY": 30000        
}

### UPDATE
PUT http://localhost:4004/odata/v4/catservice/UpdateEmpSet(104)
Content-Type: application/json

{
        "EMPID": 104,
        "EMPNAME": "Suman999999999999",
        "GENDER": "M",
        "SALARY": 22        
}

### Test Action: PromoteEmployee
POST http://localhost:4004/odata/v4/catservice/PromoteEmployee
Content-Type: application/json

{
  "EMPID": 102
}

### Test Function: HighSalaryEmployees
GET http://localhost:4004/odata/v4/catservice/HighSalaryEmployees(SALARY=2000)